version: "3"

services:
  hr-oauth: 
    build:
      context: .
      args:
        - WAR_FILE=target/hr-oauth.jar
        - CONTEXT=hr-oauth
    container_name: hr-oauth
    hostname: hr-oauth
    restart: always
    networks:
      - hr-net
      
networks:
  hr-net: 